name: Tests

# Controls when the workflow will run
on:
  pull_request:
    branches:
        - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: actions/checkout@v3
    - uses: actions/cache@v1.2.1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1.2.1
      with:
        path: ~/.cache/torch
        key: ${{ runner.os }}-cache-torch
    - uses: actions/cache@v1.2.1
      with:
        path: ~/.torch
        key: ${{ runner.os }}-torch
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3.1.4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        pip install -e .
    - name: Install tests/requirements.txt
      run: |
        function retry-with-backoff() {
          for BACKOFF in 0 1 2 4 8 16 32 64; do
            sleep $BACKOFF
            if "$@"; then
              return 0
            fi
          done
          return 1
        }
        retry-with-backoff pip install -r tests/requirements.txt
    - name: Test with pytest
      run: |
        pytest --durations=0 --verbose
